{
 "title": "FSM Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "customercode", "label": "Customer", "query": "label_values(customercode)" },
   { "name": "environmenttype", "label": "Environment", "query": "label_values(environmenttype)" }
  ]
 },
 "panels": [
  {
   "title": "Response times",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "TESTamm_http_response_duration{TESTrole=\"fsm\",customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "FSM Server health",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "TESTamm_fsm_health_check_status{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}"
    }
   ]
  },
  {
   "title": "FSM DB Health",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "TESTamm_fsm_db_health{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}"
    }
   ]
  },
  {
   "title": "FSM time stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "TESTamm_fsm_query_time{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "Query Time"
    },
    {
     "expr": "TESTamm_fsm_server_info_time{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "Info Time"
    }
   ]
  },
  {
   "title": "Monitor user account working",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "TESTamm_fsm_user_login{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}"
    }
   ]
  },
  {
   "title": "FSM Login test",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "TESTamm_fsm_smart_client_logon{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "Client Logon"
    },
    {
     "expr": "TESTamm_fsm_web_client_logon{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "Web Logon"
    }
   ]
  },
  {
   "title": "Cert expire days",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "TESTamm_http_cert{TESTrole=\"fsm\",customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "{{server}}"
    },
    { "expr": "TESTamm_http_cert_gp", "legendFormat": "gp" }
   ]
  }
 ]
}