{
 "title": "MWS Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "customercode", "label": "customer", "query": "label_values(customercode)" },
   { "name": "environmenttype", "label": "environmenttype", "query": "label_values(environmenttype)" }
  ]
 },
 "panels": [
  {
   "title": "OS CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg (rate(wmi_cpu_time_total{mode=\"idle\",customercode=~\"$customercode\"}[2m])) * 100)",
     "legendFormat": "avg cpu on cores"
    }
   ]
  },
  {
   "title": "OS Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wmi_cs_physical_memory_bytes{customercode=~\"$customercode\"}-wmi_os_physical_memory_free_bytes{customercode=~\"$customercode\"}",
     "legendFormat": "used"
    },
    {
     "expr": "wmi_cs_physical_memory_bytes{customercode=~\"$customercode\"}",
     "legendFormat": "available"
    }
   ]
  },
  {
   "title": "Server Health",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "TESTamm_mws_healthstateid{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "{{mwsserver}}"
    }
   ]
  },
  {
   "title": "Java heap usage in %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "TESTamm_mws_java_memory_usage{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "{{mwsserver}}"
    }
   ]
  },
  {
   "title": "Connection Pools",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "TESTamm_mws_fndbas_avg_wait{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "fndbas_avg_wait {{mwsserver}}"
    },
    {
     "expr": "TESTamm_mws_fndbas_currcapacity{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "fndbas_currcapacity {{mwsserver}}"
    },
    {
     "expr": "TESTamm_mws_fndbas_current_count{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "fndbas_current_count {{mwsserver}}"
    },
    {
     "expr": "TESTamm_mws_fndbas_status{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "fndbas_status {{mwsserver}}"
    }
   ]
  },
  {
   "title": "Stuck threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "TESTamm_mws_stuck_threads{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "{{mwsserver}}"
    }
   ]
  },
  {
   "title": "PLSQL pool pressure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "TESTamm_mws_plsql_switch_user_percentage{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "{{mwsserver}}: switch user %"
    },
    {
     "expr": "TESTamm_mws_plsql_waited_requests_percentage{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "{{mwsserver}}:  wait request %"
    }
   ]
  },
  {
   "title": "Status of MWS depolyments",
   "type": "stat",
   "description": "# of deployments in different states",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by (mode,mwsserver) (TESTamm_mws_applications_started{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"})",
     "legendFormat": "{{mode}} : {{mwsserver}}"
    }
   ]
  },
  {
   "title": "XA Connection Pool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "TESTamm_mws_fndbasxa_avg_wait{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "fndbasXA_avg_wait {{mwsserver}}"
    },
    {
     "expr": "TESTamm_mws_fndbasxa_currcapacity{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "fndbasXA_currcapacity {{mwsserver}}"
    },
    {
     "expr": "TESTamm_mws_fndbasxa_current_count{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "fndbasXA_current_count {{mwsserver}}"
    },
    {
     "expr": "TESTamm_mws_fndbasxa_status{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "fndbasXA_status {{mwsserver}}"
    }
   ]
  }
 ]
}