{
 "title": "Oracle DB",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "customercode", "label": "customer", "query": "label_values(customercode)" },
   { "name": "environmenttype", "label": "environmenttype", "query": "label_values(environmenttype)" }
  ]
 },
 "panels": [
  {
   "title": "OS CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg (rate(wmi_cpu_time_total{customercode=~\"$customercode\",mode=\"idle\"}[2m])) * 100)",
     "legendFormat": "cpu avg on cores"
    }
   ]
  },
  {
   "title": "OS memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wmi_cs_physical_memory_bytes{customercode=~\"$customercode\"}-wmi_os_physical_memory_free_bytes{customercode=~\"$customercode\"}",
     "legendFormat": "used"
    },
    {
     "expr": "wmi_cs_physical_memory_bytes{customercode=~\"$customercode\"}",
     "legendFormat": "physical"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Sessions" }
   ],
   "targets": [
    {
     "expr": "TESTamm_db_db_sessions{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "Sessions"
    },
    {
     "expr": "TESTamm_db_db_active_sessions{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "Active Sessions"
    },
    {
     "expr": "TESTamm_db_db_blocked_sessions{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "Blocked Sessions"
    },
    {
     "expr": "TESTamm_db_db_blocked_sessions_1s{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "Blocked Sessions 1s"
    },
    {
     "expr": "TESTamm_db_db_blocked_sessions_120s{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "Blocked Sessions 120s"
    }
   ]
  },
  {
   "title": "Max wait on Blocked Session",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "TESTamm_db_blocked_sessions_maxwaitsecs{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "max blocked session"
    }
   ]
  },
  {
   "title": "Login TESTmonitoring",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "TESTamm_db_user_login{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "Login"
    }
   ]
  },
  {
   "title": "db io",
   "type": "graph",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "LIO" }
   ],
   "targets": [
    {
     "expr": "rate(TESTamm_db_accum_logical_io{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}[2m])",
     "legendFormat": "Logical IO"
    },
    {
     "expr": "rate(TESTamm_db_accum_physical_io{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}[2m])",
     "legendFormat": "Physical IO"
    }
   ]
  },
  {
   "title": "Invalid Objects",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "TESTamm_db_invalid_bodies{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "Invalid body"
    },
    {
     "expr": "TESTamm_db_invalid_packages{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "Invalid package"
    },
    {
     "expr": "TESTamm_db_invalid_triggers{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "Invalid trigger"
    },
    {
     "expr": "TESTamm_db_invalid_views{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "Invalid view"
    },
    {
     "expr": "TESTamm_db_invalid_db_objects{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "TOTAL Invalid objects "
    }
   ]
  },
  {
   "title": "Tablespace usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "TESTamm_db_tbs_TESTapp_data{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "TESTapp_data"
    },
    {
     "expr": "TESTamm_db_tbs_TESTapp_index{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "TESTapp_index"
    },
    {
     "expr": "TESTamm_db_tbs_TESTapp_lob{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "TESTapp_lob"
    },
    {
     "expr": "TESTamm_db_tbs_system{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "system"
    },
    {
     "expr": "TESTamm_db_tbs_users{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "users"
    },
    {
     "expr": "TESTamm_db_tbs_sysaux{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "sysaux"
    },
    {
     "expr": "TESTamm_db_tbs_temp{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "temp"
    },
    {
     "expr": "TESTamm_db_tbs_undotbs{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "undotbs"
    },
    {
     "expr": "TESTamm_db_tbs_TESTapp_archive_data{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "TESTapp_archive_data"
    },
    {
     "expr": "TESTamm_db_tbs_TESTapp_archive_index{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "TESTapp_archive_index"
    },
    {
     "expr": "TESTamm_db_tbs_TESTapp_report_data{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "TESTapp_report_data"
    },
    {
     "expr": "TESTamm_db_tbs_TESTapp_report_index{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "TESTapp_report_index"
    }
   ]
  },
  {
   "title": "Oracle Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "TESTamm_db_db_buffer_cache_size{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "Buffer cache"
    },
    {
     "expr": "TESTamm_db_db_shared_pool_size{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "Shared pool"
    },
    {
     "expr": "TESTamm_db_db_pga_memory{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "pga memory"
    },
    {
     "expr": "TESTamm_db_pga_aggregate_limit{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "pga limit"
    },
    {
     "expr": "TESTamm_db_sga_target{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "sga target"
    },
    {
     "expr": "TESTamm_db_memory_target{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "memory target"
    }
   ]
  },
  {
   "title": "Resent Ora-600 errors ",
   "type": "singlestat",
   "description": "ORA- errors last 24h in Alert log",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 42 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "TESTamm_db_alert_log{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}"
    }
   ]
  },
  {
   "title": "Database uptime minutes",
   "type": "singlestat",
   "description": "in minutes",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 42 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "TESTamm_db_database_uptime{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}"
    }
   ]
  },
  {
   "title": "RMAN backup",
   "type": "singlestat",
   "description": "Minutes since last successful RMAN backup",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 42 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "TESTamm_db_rman_backup{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}"
    }
   ]
  },
  {
   "title": "Corrupt datafile blocks",
   "type": "singlestat",
   "description": "Corrupt datafile blocks",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 42 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "TESTamm_db_block_corruption{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}"
    }
   ]
  },
  {
   "title": "Invalid datafiles",
   "type": "singlestat",
   "description": "Number of datafiles not on-line",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 42 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "TESTamm_db_data_file_status{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}"
    }
   ]
  },
  {
   "title": "Byte types in objects",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 42 },
   "targets": [
    {
     "expr": "TESTamm_db_tables_byte_mode{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "Byte tables"
    },
    {
     "expr": "TESTamm_db_packages_byte_mode{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "Byte packages"
    }
   ]
  },
  {
   "title": "Index cost adj",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 42 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "TESTamm_db_index_cost_adj{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}"
    }
   ]
  },
  {
   "title": "DB type",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 42 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "TESTamm_db_pluggable{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}"
    }
   ]
  },
  {
   "title": "Compatible",
   "type": "singlestat",
   "description": "Check if paramterer compatible is different from the DB version",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 42 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "TESTamm_db_compatible{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}"
    }
   ]
  },
  {
   "title": "Opt Feature Enable",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 42 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "TESTamm_db_optimizer_features_enable{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}"
    }
   ]
  },
  {
   "title": "Packages in debug",
   "type": "singlestat",
   "description": "Packages compiled in debug mode",
   "gridPos": { "h": 3, "w": 2, "x": 21, "y": 42 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "TESTamm_db_debug_compiled_packages{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "debug compiled"
    }
   ]
  },
  {
   "title": "FRA usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 45 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "TESTamm_db_fra_usage{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "FRA usage %"
    }
   ]
  },
  {
   "title": "Size of Audit data",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 45 },
   "targets": [
    {
     "expr": "TESTamm_db_size_unified_aud{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}"
    }
   ]
  }
 ]
}