{
 "title": "PSO Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "customercode", "label": "Customer", "query": "label_values(customercode)" },
   { "name": "environmenttype", "label": "Environment", "query": "label_values(environmenttype)" }
  ]
 },
 "panels": [
  {
   "title": "PSO Availability check",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "TESTamm_pso_availability_check{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}"
    }
   ]
  },
  {
   "title": "PSO smoketest",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "TESTamm_pso_last_system_test_status{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}"
    }
   ]
  },
  {
   "title": "PSO monitor user working",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "TESTamm_pso_user_login" }
   ]
  },
  {
   "title": "Smoketest exec time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "TESTamm_pso_last_system_test_time_taken{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}"
    }
   ]
  },
  {
   "title": "PSO endpoints",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "TESTamm_http_response{TESTrole=\"pso\",customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Minutes since last smoketest",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "TESTamm_pso_elapsed_time_since_last_system_test{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}/60"
    }
   ]
  },
  {
   "title": "Cert expire days",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "TESTamm_http_cert{TESTrole=\"pso\",customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Response times",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "TESTamm_http_response_duration{TESTrole=\"pso\",customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "{{server}}"
    }
   ]
  }
 ]
}