{
 "title": "TAS Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "customercode", "label": "Customer", "query": "label_values(customercode)" },
   { "name": "environmenttype", "label": "Environment", "query": "label_values(environmenttype)" }
  ]
 },
 "panels": [
  {
   "title": "Database Accessible - SystemId",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "TESTamm_tas_post_request{customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}"
    }
   ]
  },
  {
   "title": "Cert expire days",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "TESTamm_http_cert{TESTrole=\"tas\",customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "{{server}}"
    },
    { "expr": "TESTamm_http_cert_gp", "legendFormat": "gp" }
   ]
  },
  {
   "title": "Response times",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "TESTamm_http_response_duration{TESTrole=\"tas\",customercode=~\"$customercode\",environmenttype=~\"$environmenttype\"}",
     "legendFormat": "{{server}}"
    }
   ]
  }
 ]
}