port: 9888
mode: Apps9
time_zone: Asia/Colombo
looping_interval: 3
inactivity_sleep: 7200
duration: true
cbs_site: 1
TESTInstance: prod
db_host: lkppde332.corpnet.TESTworld.com
db_instance: apps9
db_port: 1521
db_appowner: TESTapp
admin_port: 58090
domain: lkppde332
url: https://CMBGSE1907.corpnet.TESTworld.com:48080/
admin_url: http://lkppde332.corpnet.TESTworld.com:58090
pso_base_url: http://cmbpde2653
fsm_base_url: https://fsmgse512-rnd.TESTworld.com/fsm6gseLKA
mws_monit_user: TESTmon
mws_monit_pass: CgQIlyZ7Sx9JiyJwm7TdipwcHkREvi2mhA+R
pso_monit_user: TESTuser
pso_monit_pass: CgQIwaQINd2ecid84t4NMxknRMnOYGPYKaZ+
fsm_monit_user: TESTMONITORING
fsm_monit_pass: CgQI6HwK/HylmIBKZMTU6ASR+HRFatPcskhD
tas_system_id: 10w4rtmbntcmb.TESTworld.com
tas_system_url: https://uxx-rtm-test.TESTworld.com
TEST_user: TESTmonitoring
TEST_pass: CgQI0MJf9hMIUehrxVsMfnYDG9U7qdCdYY7o
db_user: TESTmonitoring
db_pass: CgQI0MJf9hMIUehrxVsMfnYDG9U7qdCdYY7o
URLS:
  RESPONSE_BI: null
  RESPONSE_CRYSTAL: http://dlk1gseapp67/Apps10Dep/TEST_ReportService.asmx?wsdl
  RESPONSE_DEMAND: http://labjse0:5010/status
  RESPONSE_TAS: https://tas-app10.TESTworld.com/
  RESPONSE_PSO_ISWB: http://cmbpde2653/TESTSchedulingWorkbench
  RESPONSE_PSO_IPWB: http://cmbpde2653/TESTPSOWorkbench
  RESPONSE_FSM_MAIN: https://fsmgse512-rnd.TESTworld.com/fsm6gseLKA/
  RESPONSE_FSM_MOBILE: https://fsmgse512-rnd.TESTworld.com/fsm6gseLKA/mobile
  RESPONSE_FSM_WEB: https://fsmgse512-rnd.TESTworld.com/fsm6gseLKA/webclient
  RESPONSE_FSM_MIS: https://fsmgse512-rnd.TESTworld.com/fsm6gseLKA/metrixintegrationservice
CERTIFICATES:
  CERT_cmbgse1907: https://CMBGSE1907.corpnet.TESTworld.com:48080
  CERT_lkppde328_apps9: https://lkppde328.corpnet.TESTworld.com:58080
  CERT_GP: https://www.gp.se/
LABELS:
  TESTINSTANCE: PROD
  TESTROLE: MWS
  TESTVERSION: APPS9
INFO:
  MANIFEST: 86400
DB:
  ACCUM_LOGICAL_IO: 60
  ACCUM_PHYSICAL_IO: 60
  ALERT_LOG: 600
  APPLICATION_SEARCH_ERROR: 600
  APPLICATION_SEARCH_SYNCH: 600
  APPL_MESSAGES_PROCESSING_2H: 600
  APPL_MESSAGES_RELEASED_2H: 600
  APPL_MESSAGES_WITH_RETRIES: 600
  APPL_SERVER_BQ_WITH_ERROR: 600
  ARCHIVING_PROCESSES: 600
  BATCH_QUEUE_ACTIVE: 600
  BATCH_QUEUE_CONFIG: 600
  BATCH_QUEUE_PROC: 600
  BLOCKED_SESSIONS: 60
  BLOCKED_SESSIONS_MAXWAITSECS: 60
  BLOCK_CORRUPTION: 7200
  BRES_NON_RESPONDING_REPORTS: 7200
  BRES_NON_RESPONDING_SERVERS: 7200
  BR_MISSING_REP_PARAM_LOV_VIEWS: 7200
  BUFFER_CACHE_SIZE: 3600
  CLEANUP_TOTAL: 600
  COMPATIBLE: 7200
  CONNECTIVITY_DB_PROCESSES: 600
  CONNECTIVITY_INBOX_ROUTING: 600
  CONNECTIVITY_OUTBOX_ROUTING: 600
  CONNECTIVITY_PROCESSES: 600
  DATABASE_UPTIME: 120
  DAYS_LEFT: 600
  DB_ACTIVE_SESSIONS: 60
  DB_BLOCKED_SESSIONS: 60
  DB_BUFFER_CACHE_SIZE: 7200
  DB_PGA_MEMORY: 600
  DB_SESSIONS: 120
  DB_SHARED_POOL_SIZE: 600
  DEBUG_COMPILED_PACKAGES: 7200
  DEFERRED_JOBS_EXECUTING_12H: 7200
  DICTIONARY_REFRESH: 7200
  ERROR_OBS: 7200
  EVENT_ACTIONS: 7200
  FND_USERS: 7200
  FRA_USAGE: 7200
  HOURS_SINCE_LAST_OBS: 7200
  TEST_ACCOUNTS: 7200
  INDEX_COST_ADJ: 7200
  INVALID_BODIES: 7200
  INVALID_DB_OBJECTS: 7200
  INVALID_PACKAGES: 7200
  INVALID_TRIGGERS: 7200
  INVALID_VIEWS: 7200
  IS_CUSTOM_ATTRIB_INV_VIEWS: 7200
  IS_CUSTOM_DIM_CONN_INV_VIEWS: 7200
  IS_CUSTOM_LOV_DIM_INV_VIEWS: 7200
  LICENSE_LIMIT: 7200
  LOGGED_ON_USERS: 600
  MANUAL_REVIEW_OBS: 7200
  MEMORY_TARGET: 7200
  MISSING_HBT_OBS: 7200
  OPTIMIZER_FEATURES_ENABLE: 7200
  PACKAGES_BYTE_MODE: 7200
  PGA_AGGREGATE_LIMIT: 7200
#  PLSQLAP_PING: 600
  PLUGGABLE: 7200
  PRINTAGENTS_REMOTE_ACTIVE: 600
  PRINTJOB_FAILED_24H: 7200
  PRINTJOB_REMOTEWAITING_15MIN: 60
  PRINTJOB_REMOTEWAITING_30MIN: 120
  PRINTJOB_WAITING_15M: 60
  PRINTJOB_WORKING_2H: 600
  QUEUE_ERROR: 60
  QUEUE_EXEC: 60
  QUEUE_PROCESSES: 600
  QUEUE_READY: 600
  QUEUE_WAIT: 600
  RECEIVED_OBS: 7200
  REFERENCE_REFRESH: 7200
  REPLICATION_PROCESSES: 7200
  REPORT_REFRESH: 7200
  RMAN_BACKUP: 7200
  ROLES_PER_USER: 7200
  SERVER_PROC_BROKEN: 600
  SERVER_PROC_TOTAL: 600
  SGA_TARGET: 7200
#  SIZE_AUD$: 7200
  SIZE_UNIFIED_AUD: 7200
  STUCK_BATCH_QUEUE_PROCESSES: 600
  TABLES_BYTE_MODE: 7200
  TBS_TESTAPP_ARCHIVE_DATA: 7200
  TBS_TESTAPP_ARCHIVE_INDEX: 7200
  TBS_TESTAPP_DATA: 7200
  TBS_TESTAPP_INDEX: 7200
  TBS_TESTAPP_LOB: 7200
  TBS_TESTAPP_REPORT_DATA: 7200
  TBS_TESTAPP_REPORT_INDEX: 7200
  TBS_SYSAUX: 7200
  TBS_SYSTEM: 7200
  TBS_TEMP: 7200
  TBS_UNDOTBS: 7200
  TBS_USERS: 7200
  UNKNOWN_OBS: 7200
  USERS_LEFT: 7200
SYSLOAD:
  REPORT_GENERATION: 600
HTTP:
  CERT_cmbgse1907: 86400
  CERT_lkppde328_apps9: 86400
  CERT_GP: 86400
#  LOGIN: 120
  RESPONSE_BI: 120
  RESPONSE_CRYSTAL: 120
  RESPONSE_DEMAND: 120
  RESPONSE_TAS: 120
  RESPONSE_PSO_ISWB: 120
  RESPONSE_PSO_IPWB: 120
  RESPONSE_FSM_MAIN: 120
  RESPONSE_FSM_MOBILE: 120
  RESPONSE_FSM_WEB: 120
  RESPONSE_FSM_MIS: 120
MWS:
  FNDBAS_STATUS: 600
  FNDBASXA_STATUS: 600
  FNDBAS_CURRCAPACITY: 600
  FNDBASXA_CURRCAPACITY: 600
  FNDBAS_CURRENT_COUNT: 600
  FNDBASXA_CURRENT_COUNT: 600
  FNDBAS_AVG_WAIT: 600
  FNDBASXA_AVG_WAIT: 600
  PLSQL_SWITCH_USER_PERCENTAGE: 600
  PLSQL_WAITED_REQUESTS_PERCENTAGE: 600
  STUCK_THREADS: 120
  HEALTHSTATEID: 600
  JAVA_MEMORY_USAGE: 120
  APPLICATIONS_STARTED: 3600
PSO:
#  AVAILABILITY_CHECK: 600
#  LAST_SYSTEM_TEST_TIME_TAKEN: 600
FSM:
  SMART_CLIENT_LOGON: 600
  WEB_CLIENT_LOGON: 600
#  HEALTH_CHECK_STATUS: 600
  QUERY_TIME: 600
  SERVER_INFO_TIME: 600
CBS:
  SERVER_HEALTH_CHECK: 600
TAS:
  SYSTEM_CERTIFICATE: 120
  POST_REQUEST: 160 
